"""Calendario Apertura 2026 incrustado como fallback."""

CALENDARIO_2026 = [
    {
        "jornada": 1,
        "fecha_inicio": "2026-07-16",
        "fecha_fin": "2026-07-18",
        "partidos": [
            {"home_team": "Necaxa", "away_team": "Atlante"},
            {"home_team": "Tijuana", "away_team": "Tigres UANL"},
            {"home_team": "Atlético de San Luis", "away_team": "Cruz Azul"},
            {"home_team": "León", "away_team": "Atlas"},
            {"home_team": "FC Juarez", "away_team": "Puebla"},
            {"home_team": "Pumas UNAM", "away_team": "Pachuca"},
            {"home_team": "Guadalajara", "away_team": "Toluca"},
            {"home_team": "Monterrey", "away_team": "Santos"},
            {"home_team": "Querétaro", "away_team": "América"},
        ],
    },
    {
        "jornada": 2,
        "fecha_inicio": "2026-07-21",
        "fecha_fin": "2026-07-26",
        "partidos": [
            {"home_team": "Cruz Azul", "away_team": "Puebla"},
            {"home_team": "Toluca", "away_team": "Pumas UNAM"},
            {"home_team": "Tigres UANL", "away_team": "Atlético de San Luis"},
            {"home_team": "Atlante", "away_team": "América"},
            {"home_team": "Tijuana", "away_team": "León"},
            {"home_team": "Guadalajara", "away_team": "FC Juarez"},
            {"home_team": "Santos", "away_team": "Atlas"},
            {"home_team": "Necaxa", "away_team": "Monterrey"},
            {"home_team": "Pachuca", "away_team": "Querétaro"},
        ],
    },
    {
        "jornada": 3,
        "fecha_inicio": "2026-07-31",
        "fecha_fin": "2026-08-02",
        "partidos": [
            {"home_team": "Puebla", "away_team": "Guadalajara"},
            {"home_team": "Atlético de San Luis", "away_team": "Tijuana"},
            {"home_team": "FC Juarez", "away_team": "Pumas UNAM"},
            {"home_team": "Querétaro", "away_team": "Tigres UANL"},
            {"home_team": "León", "away_team": "Pachuca"},
            {"home_team": "Atlas", "away_team": "Monterrey"},
            {"home_team": "Cruz Azul", "away_team": "Atlante"},
            {"home_team": "América", "away_team": "Santos"},
            {"home_team": "Toluca", "away_team": "Necaxa"},
        ],
    },
    {
        "jornada": 4,
        "fecha_inicio": "2026-08-15",
        "fecha_fin": "2026-08-17",
        "partidos": [
            {"home_team": "Atlante", "away_team": "Toluca"},
            {"home_team": "Monterrey", "away_team": "FC Juarez"},
            {"home_team": "Atlas", "away_team": "Tigres UANL"},
            {"home_team": "Pumas UNAM", "away_team": "Querétaro"},
            {"home_team": "América", "away_team": "Atlético de San Luis"},
            {"home_team": "Santos", "away_team": "Guadalajara"},
            {"home_team": "Tijuana", "away_team": "Cruz Azul"},
            {"home_team": "Necaxa", "away_team": "León"},
            {"home_team": "Pachuca", "away_team": "Puebla"},
        ],
    },
    {
        "jornada": 5,
        "fecha_inicio": "2026-08-21",
        "fecha_fin": "2026-08-23",
        "partidos": [
            {"home_team": "Puebla", "away_team": "Santos"},
            {"home_team": "FC Juarez", "away_team": "América"},
            {"home_team": "Querétaro", "away_team": "Toluca"},
            {"home_team": "Guadalajara", "away_team": "Tijuana"},
            {"home_team": "León", "away_team": "Monterrey"},
            {"home_team": "Tigres UANL", "away_team": "Atlante"},
            {"home_team": "Cruz Azul", "away_team": "Atlas"},
            {"home_team": "Atlético de San Luis", "away_team": "Pachuca"},
            {"home_team": "Pumas UNAM", "away_team": "Necaxa"},
        ],
    },
    {
        "jornada": 6,
        "fecha_inicio": "2026-08-28",
        "fecha_fin": "2026-08-30",
        "partidos": [
            {"home_team": "Necaxa", "away_team": "Cruz Azul"},
            {"home_team": "Atlante", "away_team": "León"},
            {"home_team": "Tijuana", "away_team": "Pumas UNAM"},
            {"home_team": "Atlas", "away_team": "Querétaro"},
            {"home_team": "Pachuca", "away_team": "Guadalajara"},
            {"home_team": "América", "away_team": "Puebla"},
            {"home_team": "Santos", "away_team": "Tigres UANL"},
            {"home_team": "Toluca", "away_team": "FC Juarez"},
            {"home_team": "Monterrey", "away_team": "Atlético de San Luis"},
        ],
    },
    {
        "jornada": 7,
        "fecha_inicio": "2026-09-04",
        "fecha_fin": "2026-09-06",
        "partidos": [
            {"home_team": "Puebla", "away_team": "Toluca"},
            {"home_team": "FC Juarez", "away_team": "Pachuca"},
            {"home_team": "Atlético de San Luis", "away_team": "Guadalajara"},
            {"home_team": "Querétaro", "away_team": "Monterrey"},
            {"home_team": "Tigres UANL", "away_team": "Necaxa"},
            {"home_team": "América", "away_team": "Tijuana"},
            {"home_team": "Atlas", "away_team": "Atlante"},
            {"home_team": "Pumas UNAM", "away_team": "León"},
            {"home_team": "Cruz Azul", "away_team": "Santos"},
        ],
    },
    {
        "jornada": 8,
        "fecha_inicio": "2026-09-11",
        "fecha_fin": "2026-09-13",
        "partidos": [
            {"home_team": "Necaxa", "away_team": "Puebla"},
            {"home_team": "Atlante", "away_team": "Pachuca"},
            {"home_team": "Tijuana", "away_team": "Querétaro"},
            {"home_team": "León", "away_team": "Atlético de San Luis"},
            {"home_team": "Toluca", "away_team": "Atlas"},
            {"home_team": "Cruz Azul", "away_team": "América"},
            {"home_team": "Santos", "away_team": "FC Juarez"},
            {"home_team": "Guadalajara", "away_team": "Pumas UNAM"},
            {"home_team": "Monterrey", "away_team": "Tigres UANL"},
        ],
    },
    {
        "jornada": 9,
        "fecha_inicio": "2026-09-18",
        "fecha_fin": "2026-09-20",
        "partidos": [
            {"home_team": "Puebla", "away_team": "Atlante"},
            {"home_team": "FC Juarez", "away_team": "Tigres UANL"},
            {"home_team": "Atlas", "away_team": "Pumas UNAM"},
            {"home_team": "Atlético de San Luis", "away_team": "Necaxa"},
            {"home_team": "Monterrey", "away_team": "Cruz Azul"},
            {"home_team": "América", "away_team": "Guadalajara"},
            {"home_team": "Pachuca", "away_team": "Tijuana"},
            {"home_team": "Toluca", "away_team": "Santos"},
            {"home_team": "Querétaro", "away_team": "León"},
        ],
    },
    {
        "jornada": 10,
        "fecha_inicio": "2026-09-25",
        "fecha_fin": "2026-09-27",
        "partidos": [
            {"home_team": "Atlante", "away_team": "Monterrey"},
            {"home_team": "Tijuana", "away_team": "Atlas"},
            {"home_team": "Guadalajara", "away_team": "Querétaro"},
            {"home_team": "Santos", "away_team": "Pachuca"},
            {"home_team": "Tigres UANL", "away_team": "Puebla"},
            {"home_team": "Cruz Azul", "away_team": "Toluca"},
            {"home_team": "Pumas UNAM", "away_team": "Atlético de San Luis"},
            {"home_team": "León", "away_team": "FC Juarez"},
            {"home_team": "Necaxa", "away_team": "América"},
        ],
    },
    {
        "jornada": 11,
        "fecha_inicio": "2026-10-09",
        "fecha_fin": "2026-10-11",
        "partidos": [
            {"home_team": "Querétaro", "away_team": "Atlante"},
            {"home_team": "Puebla", "away_team": "León"},
            {"home_team": "Tigres UANL", "away_team": "Toluca"},
            {"home_team": "FC Juarez", "away_team": "Tijuana"},
            {"home_team": "Atlas", "away_team": "Guadalajara"},
            {"home_team": "América", "away_team": "Monterrey"},
            {"home_team": "Pachuca", "away_team": "Necaxa"},
            {"home_team": "Atlético de San Luis", "away_team": "Santos"},
            {"home_team": "Pumas UNAM", "away_team": "Cruz Azul"},
        ],
    },
    {
        "jornada": 12,
        "fecha_inicio": "2026-10-16",
        "fecha_fin": "2026-10-18",
        "partidos": [
            {"home_team": "Necaxa", "away_team": "Atlas"},
            {"home_team": "Atlante", "away_team": "Pumas UNAM"},
            {"home_team": "Tijuana", "away_team": "Puebla"},
            {"home_team": "Guadalajara", "away_team": "Tigres UANL"},
            {"home_team": "Santos", "away_team": "Querétaro"},
            {"home_team": "León", "away_team": "América"},
            {"home_team": "Toluca", "away_team": "Atlético de San Luis"},
            {"home_team": "Cruz Azul", "away_team": "FC Juarez"},
            {"home_team": "Monterrey", "away_team": "Pachuca"},
        ],
    },
    {
        "jornada": 13,
        "fecha_inicio": "2026-10-20",
        "fecha_fin": "2026-10-21",
        "partidos": [
            {"home_team": "Atlético de San Luis", "away_team": "Querétaro"},
            {"home_team": "FC Juarez", "away_team": "Atlante"},
            {"home_team": "Tigres UANL", "away_team": "León"},
            {"home_team": "Guadalajara", "away_team": "Necaxa"},
            {"home_team": "Puebla", "away_team": "Monterrey"},
            {"home_team": "Atlas", "away_team": "América"},
            {"home_team": "Toluca", "away_team": "Tijuana"},
            {"home_team": "Pachuca", "away_team": "Cruz Azul"},
            {"home_team": "Santos", "away_team": "Pumas UNAM"},
        ],
    },
    {
        "jornada": 14,
        "fecha_inicio": "2026-10-23",
        "fecha_fin": "2026-10-25",
        "partidos": [
            {"home_team": "Necaxa", "away_team": "FC Juarez"},
            {"home_team": "Atlante", "away_team": "Atlético de San Luis"},
            {"home_team": "León", "away_team": "Toluca"},
            {"home_team": "Monterrey", "away_team": "Guadalajara"},
            {"home_team": "Pumas UNAM", "away_team": "Tigres UANL"},
            {"home_team": "Atlas", "away_team": "Puebla"},
            {"home_team": "América", "away_team": "Pachuca"},
            {"home_team": "Querétaro", "away_team": "Cruz Azul"},
            {"home_team": "Tijuana", "away_team": "Santos"},
        ],
    },
    {
        "jornada": 15,
        "fecha_inicio": "2026-10-30",
        "fecha_fin": "2026-11-01",
        "partidos": [
            {"home_team": "Atlético de San Luis", "away_team": "Atlas"},
            {"home_team": "FC Juarez", "away_team": "Querétaro"},
            {"home_team": "Puebla", "away_team": "Pumas UNAM"},
            {"home_team": "Pachuca", "away_team": "Tigres UANL"},
            {"home_team": "Guadalajara", "away_team": "Atlante"},
            {"home_team": "Monterrey", "away_team": "Tijuana"},
            {"home_team": "América", "away_team": "Toluca"},
            {"home_team": "Santos", "away_team": "Necaxa"},
            {"home_team": "Cruz Azul", "away_team": "León"},
        ],
    },
    {
        "jornada": 16,
        "fecha_inicio": "2026-11-06",
        "fecha_fin": "2026-11-08",
        "partidos": [
            {"home_team": "Atlético de San Luis", "away_team": "FC Juarez"},
            {"home_team": "Necaxa", "away_team": "Tijuana"},
            {"home_team": "Atlante", "away_team": "Santos"},
            {"home_team": "Atlas", "away_team": "Pachuca"},
            {"home_team": "Tigres UANL", "away_team": "Cruz Azul"},
            {"home_team": "Toluca", "away_team": "Monterrey"},
            {"home_team": "Pumas UNAM", "away_team": "América"},
            {"home_team": "Querétaro", "away_team": "Puebla"},
            {"home_team": "León", "away_team": "Guadalajara"},
        ],
    },
    {
        "jornada": 17,
        "fecha_inicio": "2026-11-20",
        "fecha_fin": "2026-11-22",
        "partidos": [
            {"home_team": "Puebla", "away_team": "Atlético de San Luis"},
            {"home_team": "FC Juarez", "away_team": "Atlas"},
            {"home_team": "Tijuana", "away_team": "Atlante"},
            {"home_team": "Santos", "away_team": "León"},
            {"home_team": "Pachuca", "away_team": "Toluca"},
            {"home_team": "Pumas UNAM", "away_team": "Monterrey"},
            {"home_team": "Tigres UANL", "away_team": "América"},
            {"home_team": "Guadalajara", "away_team": "Cruz Azul"},
            {"home_team": "Querétaro", "away_team": "Necaxa"},
        ],
    },
]
