#!/usr/bin/env python3
"""
telegram_pronosticos.py — Alertas de Telegram con PRONÓSTICOS REALES.

Este archivo es ahora un wrapper del paquete src.telegram para mantener
compatibilidad con los scripts existentes y los tests unitarios.
"""

from src.telegram import (
    enviar_mensaje,
    enviar_pronosticos,
    enviar_resumen_rentabilidad,
    enviar_momios_estado,
    enviar_recordatorio_si_aplica,
    enviar_analisis_jornada,
    enviar_seguimiento,
    enviar_plan,
    enviar_prueba,
    enviar_confianza,
    enviar_derrotas,
    enviar_ganadores,
    proxima_jornada,
    construir_mensaje,
    construir_mensaje_seguimiento,
    _dividir_mensaje,
    _cargar_calendario_local,
    _cerca_de_jornada,
    _plan_temporada,
    _usados_persistidos,
    _partidos_jugados_torneo,
    _jornada_actual_num,
    _rec_desde_plan,
    _mapa_horarios,
    requests,
    motor,
    _contexto_top_pick,
    _alerta_xi,
    _falta_en_xi,
    _formatear_contexto,
    _ajustar_pick_top,
    _norm_simple,
    _jugadores_seguir_partido,
    _porteros_partido,
    _pct,
    _fecha_mx,
    _linea_goles,
    _totales_jornada,
    construir_mensaje_momios,
    construir_recordatorio,
    render_partidos,
    construir_mensaje_plan,
    construir_mensaje_rentabilidad,
    construir_mensaje_prueba,
    construir_mensaje_confianza,
    construir_mensaje_derrotas,
    _marcador_a_favor,
    construir_mensaje_survivor_historial,
    construir_mensaje_ganadores,
    render_survivor,
)

__all__ = [
    "enviar_mensaje",
    "enviar_pronosticos",
    "enviar_resumen_rentabilidad",
    "enviar_momios_estado",
    "enviar_recordatorio_si_aplica",
    "enviar_analisis_jornada",
    "enviar_seguimiento",
    "enviar_plan",
    "enviar_prueba",
    "enviar_confianza",
    "enviar_derrotas",
    "enviar_ganadores",
    "proxima_jornada",
    "construir_mensaje",
    "construir_mensaje_seguimiento",
    "_dividir_mensaje",
    "_cargar_calendario_local",
    "_cerca_de_jornada",
    "_plan_temporada",
    "_usados_persistidos",
    "_partidos_jugados_torneo",
    "_jornada_actual_num",
    "_rec_desde_plan",
    "_mapa_horarios",
    "requests",
    "motor",
    "_contexto_top_pick",
    "_alerta_xi",
    "_falta_en_xi",
    "_formatear_contexto",
    "_ajustar_pick_top",
    "_norm_simple",
    "_jugadores_seguir_partido",
    "_porteros_partido",
    "_pct",
    "_fecha_mx",
    "_linea_goles",
    "_totales_jornada",
    "construir_mensaje_momios",
    "construir_recordatorio",
    "render_partidos",
    "construir_mensaje_plan",
    "construir_mensaje_rentabilidad",
    "construir_mensaje_prueba",
    "construir_mensaje_confianza",
    "construir_mensaje_derrotas",
    "_marcador_a_favor",
    "construir_mensaje_survivor_historial",
    "construir_mensaje_ganadores",
    "render_survivor",
]

if __name__ == "__main__":
    res = enviar_pronosticos()
    print(f"Enviado: {res['enviado']} | pronósticos: {res['total_pronosticos']} | fuente: {res['fuente']}")
